// Generated java file - release 0.2 - do not edit !
// Copyright August 16, 1996, KUL and CUM
// Authors: Bart Demoen and Paul Tarau

package SxxMachine;

class pred_genjavaforpred_1_consts {
    Code entry_code;
    Code unify3cont;
    final static String string0 = Const.strIntern("cut");
    final static String string1 = Const.strIntern("genjavaforpred");
    final static String string2 = Const.strIntern("unify");
    final static String string3 = Const.strIntern(".");
    final static String string4 = Const.strIntern("getPredHeader");
    final static String string5 = Const.strIntern("functor");
    final static String string6 = Const.strIntern("is");
    final static String string7 = Const.strIntern("-");
    final static String string8 = Const.strIntern("changeIllegalTerms");
    final static String string9 = Const.strIntern("toJavaClassName");
    final static String string10 = Const.strIntern("genFileName");
    final static String string11 = Const.strIntern("getData");
    final static String string12 = Const.strIntern("cut");
    final static String string13 = Const.strIntern("shouldDisableIndexing");
    final static String string14 = Const.strIntern("tell");
    final static String string15 = Const.strIntern("prelude");
    final static String string16 = Const.strIntern("printHeading");
    final static String string17 = Const.strIntern("writel");
    final static String string18 = Const.strIntern("printDataClass");
    final static String string19 = Const.strIntern("public class ");
    final static String string20 = Const.strIntern(" extends Code {");
    final static String string21 = Const.strIntern("wr");
    final static String string22 = Const.strIntern("nl");
    final static String string23 = Const.strIntern("printMainConstruction");
    final static String string24 = Const.strIntern("declforeachclause");
    final static String string25 = Const.strIntern("  public void init(PredikatenPrologMachine mach) {");
    final static String string26 = Const.strIntern("    consts.entry_code = this;");
    final static String string27 = Const.strIntern("initforeachcontinuation");
    final static String string28 = Const.strIntern("}");
    final static String string29 = Const.strIntern("  @Override public int arity() { return ");
    final static String string30 = Const.strIntern(" ; }");
    final static String string31 = Const.strIntern("  @Override");
    final static String string32 = Const.strIntern("  @SuppressWarnings(\"static-access\")");
    final static String string33 = Const.strIntern("  public Code exec(PrologMachine mach) {");
    final static String string34 = Const.strIntern("printMainExec");
    final static String string35 = Const.strIntern("[]");
    final static String string36 = Const.strIntern("checkClauses");
    final static String string37 = Const.strIntern("told");
    final static Int posint1 = JpFactory.Long(1);
}

public class pred_genjavaforpred_1 extends Code {
    private final pred_genjavaforpred_1_consts consts;

    public pred_genjavaforpred_1() {
        consts = new pred_genjavaforpred_1_consts();
        initAlternatives();
    }

    protected pred_genjavaforpred_1(pred_genjavaforpred_1 c) {
        consts = c.getConsts();
        ALT = null;
    }

    protected final pred_genjavaforpred_1_consts getConsts() {
        return consts;
    }

    private static Alternatives ALT = null;

    private void initAlternatives() {
    }

    @Override
    public void init(PredikatenPrologMachine mach) {
        consts.entry_code = this;
        consts.unify3cont = mach.loadPred("unify", 2);
    }

    @Override
    public int arity() {
        return 1;
    }

    @Override
    @SuppressWarnings("static-access")
    public Code exec(PrologMachine mach) {
        Term local_aregs[] = mach.getAreg();
        Term continuation = local_aregs[1];
        Term areg0 = local_aregs[0].dref();
        Term var14 = JpFactory.JVAR(mach);
        Term var13 = JpFactory.JVAR(mach);
        Term var12 = JpFactory.JVAR(mach);
        Term var11 = JpFactory.JVAR(mach);
        Term var10 = JpFactory.JVAR(mach);
        Term var9 = JpFactory.JVAR(mach);
        Term var8 = JpFactory.JVAR(mach);
        Term var7 = JpFactory.JVAR(mach);
        Term var6 = JpFactory.JVAR(mach);
        Term var5 = JpFactory.JVAR(mach);
        Term var4 = JpFactory.JVAR(mach);
        Term var3 = JpFactory.JVAR(mach);
        Term var2 = JpFactory.JVAR(mach);
        Term var1 = JpFactory.JVAR(mach);
        if (!(areg0.unify(var1)))
            return mach.Fail0;
        local_aregs[0] = JpFactory.S(getConsts().string3, var2, var3);
        local_aregs[1] = var1.dref();
        local_aregs[2] = JpFactory.S(getConsts().string4, var2.dref(), var4, var5, JpFactory
                .S(getConsts().string5, var4.dref(), var6, var7, JpFactory.S(getConsts().string6, var8, JpFactory
                        .S(getConsts().string7, var7.dref(), getConsts().posint1), JpFactory
                                .S(getConsts().string8, var9, var6.dref(), JpFactory.S(getConsts().string9, var9
                                        .dref(), var8.dref(), var10, JpFactory.S(getConsts().string10, var10
                                                .dref(), var11, JpFactory.S(getConsts().string11, var1
                                                        .dref(), var12, var13, var14, JpFactory
                                                                .S(getConsts().string0, new HeapChoice(mach
                                                                        .getCUTB()), JpFactory
                                                                                .S(getConsts().string13, var10
                                                                                        .dref(), var6.dref(), var8
                                                                                                .dref(), var1
                                                                                                        .dref(), JpFactory
                                                                                                                .S(getConsts().string14, var11
                                                                                                                        .dref(), JpFactory
                                                                                                                                .S(getConsts().string15, JpFactory
                                                                                                                                        .S(getConsts().string0, new HeapChoice(
                                                                                                                                                mach.getCUTB()), JpFactory
                                                                                                                                                        .S(getConsts().string16, JpFactory
                                                                                                                                                                .S(getConsts().string17, JpFactory
                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                .S(getConsts().string18, var10
                                                                                                                                                                                        .dref(), var12
                                                                                                                                                                                                .dref(), var9
                                                                                                                                                                                                        .dref(), var7
                                                                                                                                                                                                                .dref(), var13
                                                                                                                                                                                                                        .dref(), var14
                                                                                                                                                                                                                                .dref()), JpFactory
                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                .CONST(getConsts().string19), JpFactory
                                                                                                                                                                                                                                                        .S(getConsts().string3, var10
                                                                                                                                                                                                                                                                .dref(), JpFactory
                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                .CONST(getConsts().string20), JpFactory
                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                        .S(getConsts().string23, var10
                                                                                                                                                                                                                                                                                                                                .dref()), JpFactory
                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string24, var1
                                                                                                                                                                                                                                                                                                                                                        .dref(), getConsts().posint1, var10
                                                                                                                                                                                                                                                                                                                                                                .dref()), JpFactory
                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string25), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string26), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string27, var12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .dref(), var9
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .dref(), var7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .dref()), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string28), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string29), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, var8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .dref(), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string30), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string31), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string32), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string33), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string34, var1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .dref(), var7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .dref(), var13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .dref()), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string28), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string28), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string3, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string21, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .CONST(getConsts().string22)), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .CONST(getConsts().string35))))))))))))))))))))))))))))))))), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string36, var1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .dref(), var10
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .dref(), var13
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .dref(), JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .S(getConsts().string37, JpFactory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .S(getConsts().string0, new HeapChoice(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mach.getCUTB()), continuation)))))))))))))))));
        mach.updateCUTB();
        return getConsts().unify3cont;

    }
}
